CREATE DATABASE HOUSING ;

USE HOUSING ;

--------------------------CLEANING DATA IN SQL QUERY---------------------

SELECT * FROM HOUSING ;


--- 1. STANDARDIZE DATE FORMAT 
SELECT SALEDATE  , CONVERT(DATE , SALEDATE) AS S_DATE FROM HOUSING ;

ALTER TABLE HOUSING 
ADD  SETDATE_CONV DATE ;


UPDATE HOUSING 
SET SETDATE_CONV = CONVERT(DATE , SALEDATE) ;


---2. POPULATE PROPERTY ADDRESS DATA 

SELECT A.PARCELID , A.PROPERTYADDRESS , B.PARCELID , B.PROPERTYADDRESS , ISNULL(A.PROPERTYADDRESS , B.PROPERTYADDRESS)
FROM HOUSING A
JOIN HOUSING B 
ON A.PARCELID = B.PARCELID 
AND A.UNIQUEID <> B.UNIQUEID
WHERE A.PROPERTYADDRESS IS NULL  ;


UPDATE A 
SET PROPERTYADDRESS = ISNULL(A.PROPERTYADDRESS , B.PROPERTYADDRESS)
FROM HOUSING A
JOIN HOUSING B 
ON A.PARCELID = B.PARCELID 
AND A.UNIQUEID <> B.UNIQUEID 
WHERE A.PROPERTYADDRESS IS NULL ;



----3.  BREAKING OUT PROPERTY ADDRESS INTO INDIVISUAL COLUMNS (ADDRESS , CITY , STATE ) 

SELECT PROPERTYADDRESS FROM HOUSING ;

SELECT SUBSTRING(PROPERTYADDRESS , 1, CHARINDEX(',' , PROPERTYADDRESS)-1) AS ADDRESS , 
SUBSTRING(PROPERTYADDRESS , CHARINDEX(',',PROPERTYADDRESS)+1 , LEN(PROPERTYADDRESS)) AS CITY FROM HOUSING ;



ALTER TABLE HOUSING 
ADD ADDRESS VARCHAR(50) ;

UPDATE HOUSING
SET ADDRESS = SUBSTRING(PROPERTYADDRESS , 1 , CHARINDEX(',' , PROPERTYADDRESS)-1) ;

ALTER TABLE HOUSING
ADD CITY VARCHAR(50) ;

UPDATE HOUSING 
SET CITY  = SUBSTRING(PROPERTYADDRESS , CHARINDEX(',' , PROPERTYADDRESS)+1 , LEN(PROPERTYADDRESS)) ;


---4. CHANGE YES & NO INTO Y & N SOLDASVACANT 

SELECT SOLDASVACANT , COUNT(*) 
FROM HOUSING
GROUP BY SOLDASVACANT ;

UPDATE HOUSING 
SET SOLDASVACANT = 'NO'
WHERE SOLDASVACANT = 'N' ; 


UPDATE HOUSING 
SET SOLDASVACANT = 'YES'
WHERE SOLDASVACANT = 'Y' ; 


---5. REMOVE DUPLICATES 

WITH ROWCTE AS
(SELECT * , ROW_NUMBER() OVER(PARTITION BY UNIQUEID , PARCELID ,PROPERTYADDRESS , SALEPRICE , SALEDATE , LEGALREFERENCE 
    ORDER BY UNIQUEID) AS ROW_NUM FROM HOUSING AS ROW_NUM) 
DELETE FROM ROWCTE
 WHERE ROW_NUM =2 ;

 --- 6. DELETE UNUSED COLUMN

 ALTER TABLE HOUSING
 DROP COLUMN  TAXDISTRICT ,PROPERTYADDRESS , SALEDATE ;











